/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as MailRouteImport } from './routes/mail'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppGapsRouteImport } from './routes/_app.gaps'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as PlacesPlaceIdRouteImport } from './routes/places.$placeId'
import { Route as AppRouteIndexRouteImport } from './routes/_app/route/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPlaceIdRoute = PlacesPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => PlacesRoute,
} as any)
const AppRouteIndexRoute = AppRouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/developers': typeof DevelopersRoute
  '/mail': typeof MailRoute
  '/ops': typeof OpsRoute
  '/places': typeof PlacesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/replay': typeof ReplayRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/gaps': typeof AppGapsRoute
  '/timetable': typeof AppTimetableRoute
  '/today': typeof AppTodayRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/route/': typeof AppRouteIndexRoute
}
export interface FileRoutesByTo {
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/developers': typeof DevelopersRoute
  '/mail': typeof MailRoute
  '/ops': typeof OpsRoute
  '/places': typeof PlacesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/replay': typeof ReplayRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/gaps': typeof AppGapsRoute
  '/timetable': typeof AppTimetableRoute
  '/today': typeof AppTodayRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/': typeof AppIndexRoute
  '/route': typeof AppRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/ai': typeof AiRoute
  '/developers': typeof DevelopersRoute
  '/mail': typeof MailRoute
  '/ops': typeof OpsRoute
  '/places': typeof PlacesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/replay': typeof ReplayRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_app/gaps': typeof AppGapsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/today': typeof AppTodayRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/route/': typeof AppRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai'
    | '/developers'
    | '/mail'
    | '/ops'
    | '/places'
    | '/privacy'
    | '/replay'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trust'
    | '/gaps'
    | '/timetable'
    | '/today'
    | '/oauth/consent'
    | '/places/$placeId'
    | '/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accessibility'
    | '/ai'
    | '/developers'
    | '/mail'
    | '/ops'
    | '/places'
    | '/privacy'
    | '/replay'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trust'
    | '/gaps'
    | '/timetable'
    | '/today'
    | '/oauth/consent'
    | '/places/$placeId'
    | '/'
    | '/route'
  id:
    | '__root__'
    | '/_app'
    | '/accessibility'
    | '/ai'
    | '/developers'
    | '/mail'
    | '/ops'
    | '/places'
    | '/privacy'
    | '/replay'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trust'
    | '/_app/gaps'
    | '/_app/timetable'
    | '/_app/today'
    | '/oauth/consent'
    | '/places/$placeId'
    | '/_app/'
    | '/_app/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AiRoute: typeof AiRoute
  DevelopersRoute: typeof DevelopersRoute
  MailRoute: typeof MailRoute
  OpsRoute: typeof OpsRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReplayRoute: typeof ReplayRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaps': {
      id: '/_app/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/_app/route/': {
      id: '/_app/route/'
      path: '/route'
      fullPath: '/route/'
      preLoaderRoute: typeof AppRouteIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGapsRoute: typeof AppGapsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRouteIndexRoute: typeof AppRouteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGapsRoute: AppGapsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppRouteIndexRoute: AppRouteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlacesRouteChildren {
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AiRoute: AiRoute,
  DevelopersRoute: DevelopersRoute,
  MailRoute: MailRoute,
  OpsRoute: OpsRoute,
  PlacesRoute: PlacesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReplayRoute: ReplayRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
