/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as OAuthConsentRouteImport } from './routes/oauth.consent'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppGapsRouteImport } from './routes/_app.gaps'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppRouteIndexRouteImport } from './routes/_app/route/index'

const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const OAuthConsentRoute = OAuthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppRouteIndexRoute = AppRouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/developers': typeof DevelopersRoute
  '/gaps': typeof AppGapsRoute
  '/oauth/consent': typeof OAuthConsentRoute
  '/replay': typeof ReplayRoute
  '/timetable': typeof AppTimetableRoute
  '/today': typeof AppTodayRoute
  '/route/': typeof AppRouteIndexRoute
}
export interface FileRoutesByTo {
  '/developers': typeof DevelopersRoute
  '/gaps': typeof AppGapsRoute
  '/oauth/consent': typeof OAuthConsentRoute
  '/replay': typeof ReplayRoute
  '/timetable': typeof AppTimetableRoute
  '/today': typeof AppTodayRoute
  '/': typeof AppIndexRoute
  '/route': typeof AppRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/developers': typeof DevelopersRoute
  '/oauth/consent': typeof OAuthConsentRoute
  '/replay': typeof ReplayRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/gaps': typeof AppGapsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/': typeof AppIndexRoute
  '/_app/route/': typeof AppRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developers'
    | '/gaps'
    | '/oauth/consent'
    | '/replay'
    | '/timetable'
    | '/today'
    | '/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/developers'
    | '/gaps'
    | '/oauth/consent'
    | '/replay'
    | '/timetable'
    | '/today'
    | '/'
    | '/route'
  id:
    | '__root__'
    | '/developers'
    | '/oauth/consent'
    | '/replay'
    | '/_app'
    | '/_app/gaps'
    | '/_app/timetable'
    | '/_app/today'
    | '/_app/'
    | '/_app/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevelopersRoute: typeof DevelopersRoute
  OAuthConsentRoute: typeof OAuthConsentRoute
  ReplayRoute: typeof ReplayRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OAuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaps': {
      id: '/_app/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/route/': {
      id: '/_app/route/'
      path: '/route'
      fullPath: '/route/'
      preLoaderRoute: typeof AppRouteIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGapsRoute: typeof AppGapsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRouteIndexRoute: typeof AppRouteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGapsRoute: AppGapsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppRouteIndexRoute: AppRouteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DevelopersRoute: DevelopersRoute,
  OAuthConsentRoute: OAuthConsentRoute,
  ReplayRoute: ReplayRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
